.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. denemecoin_qt test_denemecoin_qt
clean: FORCE
	$(MAKE) -C .. denemecoin_qt_clean test_denemecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_denemecoin_qt_check
denemecoin-qt denemecoin-qt.exe: FORCE
	 $(MAKE) -C .. denemecoin_qt
